### ISSUE TITLE
Postgresql support for pyquibase is broken

### ISSUE THREAD

**Issue by mduwalsh** [rampart81/pyquibase#2]
'postgresql' class method in pyquibase.py is setting database to 'mysql'.
'postgresql-42.1.3.jar' is not downloaded when you install using pip. Missing setting for it in setup.py.

**Comment by rampart81** [comment]
@mduwalsh Sorry for the late response! This issue has been fixed by @ssmi1975 PR #1 . I just updated and uploaded the latest package to pypl as ver 1.1 . Please let me know if there is any other issue.

**Comment by mduwalsh** [comment]
@rampart81 I am not able to download version 1.1 using pip. However I can see the release is there in pypi.

**Comment by rampart81** [comment]
@mduwalsh Just uploaded it again to pypi with version 1.2. It will take some time for pypi to index it but you should be able to download it by running `pip install pyquibase==1.2`.

**Comment by mduwalsh** [comment]
@rampart81 Thank you. I am able to download ver-1.2.
